import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../constants.dart';

class AnalysisScreen extends StatefulWidget {
  final Map<String, dynamic> result;

  const AnalysisScreen({super.key, required this.result});

  @override
  State<AnalysisScreen> createState() => _AnalysisScreenState();
}

class _AnalysisScreenState extends State<AnalysisScreen> {
  bool logSaved = false;

  // SAVE SKIN LOG
  Future<void> saveSkinLog(int score, String issue) async {
    if (logSaved) return;

    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    await FirebaseFirestore.instance
        .collection("users")
        .doc(user.uid)
        .collection("skin_logs")
        .add({
      "date": Timestamp.now(),
      "score": score,
      "issue": issue,
      "note": "Auto log after scan"
    });

    logSaved = true;
  }

  // OPEN PRODUCT
  Future<void> openProduct(String link) async {
    final Uri url = Uri.parse(link);
    await launchUrl(url, mode: LaunchMode.externalApplication);
  }

  @override
  Widget build(BuildContext context) {
    final result = widget.result;

    final List recommendations = result["recommendations"] ?? [];
    final String condition = result["issue"] ?? "Unknown";
    final String description =
        result["description"] ?? "No description available";
    final double confidence =
    (result["confidence"] ?? 0).toDouble();
    final bool consultDerm =
        result["consult_dermatologist"] ?? false;
    final int skinScore = result["skin_score"] ?? 0;
    final String severity = result["severity"] ?? "Unknown";

    final String riskLevel =
    consultDerm ? "High - See Dermatologist" : "Low";

    saveSkinLog(skinScore, condition);

    return Scaffold(
      backgroundColor: AppColors.background,

      appBar: AppBar(
        elevation: 0,
        backgroundColor: Colors.white,
        title: Text(
          "Skin Analysis Result",
          style: GoogleFonts.outfit(
            fontWeight: FontWeight.w700,
            color: AppColors.textDark,
          ),
        ),
      ),

      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),

        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [

            // SCORE CARD
            _scoreCard(skinScore, severity),

            const SizedBox(height: 20),

            // DETAILS CARD
            _detailsCard(
              condition,
              confidence,
              riskLevel,
              description,
            ),

            const SizedBox(height: 25),

            // TITLE
            Text(
              "Recommended Routine",
              style: GoogleFonts.outfit(
                fontSize: 22,
                fontWeight: FontWeight.w800,
                color: AppColors.textDark,
              ),
            ),

            const SizedBox(height: 15),

            // PRODUCTS
            if (recommendations.isNotEmpty)
              buildRecommendations(recommendations)
            else
              Text(
                "No recommendations available",
                style: GoogleFonts.poppins(
                  color: AppColors.textLight,
                ),
              ),

            const SizedBox(height: 20),

            // 🔥 DISCLAIMER
            Container(
              padding: const EdgeInsets.symmetric(
                horizontal: 14,
                vertical: 12,
              ),
              decoration: BoxDecoration(
                color: Colors.grey.withOpacity(0.08),
                borderRadius: BorderRadius.circular(14),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [

                  const Text(
                    "⚠️",
                    style: TextStyle(fontSize: 14),
                  ),

                  const SizedBox(width: 8),

                  Expanded(
                    child: Text(
                      "This result is generated by AI and is for informational purposes only.",
                      style: GoogleFonts.poppins(
                        fontSize: 12,
                        color: AppColors.textLight,
                        height: 1.4,
                      ),
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 30),
          ],
        ),
      ),
    );
  }

  // SCORE CARD
  Widget _scoreCard(int score, String severity) {
    return Container(
      padding: const EdgeInsets.all(20),

      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          )
        ],
      ),

      child: Row(
        children: [

          Container(
            width: 70,
            height: 70,
            decoration: BoxDecoration(
              color: AppColors.primary.withOpacity(.1),
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Text(
                "$score",
                style: GoogleFonts.outfit(
                  fontSize: 26,
                  fontWeight: FontWeight.w800,
                  color: AppColors.primary,
                ),
              ),
            ),
          ),

          const SizedBox(width: 20),

          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [

              Text(
                "Skin Health Score",
                style: GoogleFonts.poppins(
                  fontSize: 14,
                  color: AppColors.textLight,
                ),
              ),

              const SizedBox(height: 4),

              Text(
                "$score / 100",
                style: GoogleFonts.outfit(
                  fontSize: 22,
                  fontWeight: FontWeight.w700,
                  color: AppColors.textDark,
                ),
              ),

              const SizedBox(height: 4),

              Text(
                "Severity: $severity",
                style: GoogleFonts.poppins(
                  fontSize: 13,
                  color: AppColors.textLight,
                ),
              ),
            ],
          )
        ],
      ),
    );
  }

  // DETAILS CARD
  Widget _detailsCard(
      String condition,
      double confidence,
      String riskLevel,
      String description) {

    return Container(
      padding: const EdgeInsets.all(20),

      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          )
        ],
      ),

      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [

          _rowItem("Condition", condition),

          _rowItem(
            "Confidence",
            "${(confidence * 100).toStringAsFixed(1)} %",
          ),

          _rowItem("Risk Level", riskLevel),

          const SizedBox(height: 10),

          Text(
            "Description",
            style: GoogleFonts.poppins(
              fontWeight: FontWeight.w600,
              color: AppColors.textDark,
            ),
          ),

          const SizedBox(height: 6),

          Text(
            description,
            style: GoogleFonts.poppins(
              fontSize: 14,
              color: AppColors.textLight,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }

  Widget _rowItem(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),

      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [

          Text(
            label,
            style: GoogleFonts.poppins(
              fontWeight: FontWeight.w600,
              color: AppColors.textDark,
            ),
          ),

          Text(
            value,
            style: GoogleFonts.poppins(
              color: AppColors.textLight,
            ),
          ),
        ],
      ),
    );
  }

  // RECOMMENDATIONS
  Widget buildRecommendations(List products) {
    return Column(
      children: products.map<Widget>((p) {

        return Container(
          margin: const EdgeInsets.only(bottom: 12),

          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(.05),
                blurRadius: 8,
              )
            ],
          ),

          child: ListTile(
            title: Text(
              p["name"] ?? "Product",
              style: GoogleFonts.poppins(
                fontWeight: FontWeight.w600,
              ),
            ),

            subtitle: Text(
              p["step"] ?? "",
              style: GoogleFonts.poppins(
                color: AppColors.textLight,
              ),
            ),

            trailing: const Icon(Icons.open_in_new_rounded),

            onTap: () {
              if (p["link"] != null) {
                openProduct(p["link"]);
              }
            },
          ),
        );

      }).toList(),
    );
  }
}